#!/usr/bin/env node
require("source-map-support").install();
const minimist = require("minimist");
const { kubeBuild } = require("../dist/index.js");

const options = minimist(process.argv.slice(2));
kubeBuild(options)
  .then(code => {
    process.exit(code);
  })
  .catch(() => {
    process.exit(1);
  });
